/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const FrequencyType = IDL.Variant({
  'none' : IDL.Null,
  'monthly' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const TaskStatus = IDL.Variant({
  'done' : IDL.Null,
  'todo' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'assignee' : IDL.Principal,
  'frequencyDays' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'targetDate' : IDL.Text,
  'priority' : Priority,
  'frequency' : FrequencyType,
  'department' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const UserProfileEntry = IDL.Record({
  'principal' : IDL.Principal,
  'profile' : UserProfile,
});
export const CompletionDate = IDL.Record({
  'taskId' : IDL.Nat,
  'completionTimestamp' : IDL.Int,
});
export const TaskPauseState = IDL.Record({
  'pausedAt' : IDL.Text,
  'unpausedAt' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignUserRoleAsAdmin' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignSuperUserRole' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'bootstrapAdmin' : IDL.Func([], [IDL.Bool], []),
  'countTasksByStatus' : IDL.Func([], [IDL.Nat, IDL.Nat, IDL.Nat], ['query']),
  'createTask' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Principal,
        IDL.Text,
        Priority,
        FrequencyType,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteTask' : IDL.Func([IDL.Nat], [], []),
  'getAdminCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfileEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCompletionDates' : IDL.Func([], [IDL.Vec(CompletionDate)], ['query']),
  'getMyTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
  'getTaskInstanceCompletions' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int))],
      ['query'],
    ),
  'getTaskInstanceRemarks' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getTaskInstanceTimingStatuses' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
      ['query'],
    ),
  'getTaskPauseStates' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, TaskPauseState))],
      ['query'],
    ),
  'getTasksByEmployee' : IDL.Func([IDL.Principal], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasAnyAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerSuperUser' : IDL.Func([], [IDL.Bool], ['query']),
  'markTaskInstanceDone' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'pauseTask' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setTaskInstanceRemarks' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'setTaskInstanceTimingStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'unmarkTaskInstanceDone' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'unpauseTask' : IDL.Func([IDL.Nat], [], []),
  'updateTaskDetails' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const FrequencyType = IDL.Variant({
    'none' : IDL.Null,
    'monthly' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const TaskStatus = IDL.Variant({
    'done' : IDL.Null,
    'todo' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'assignee' : IDL.Principal,
    'frequencyDays' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'targetDate' : IDL.Text,
    'priority' : Priority,
    'frequency' : FrequencyType,
    'department' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const UserProfileEntry = IDL.Record({
    'principal' : IDL.Principal,
    'profile' : UserProfile,
  });
  const CompletionDate = IDL.Record({
    'taskId' : IDL.Nat,
    'completionTimestamp' : IDL.Int,
  });
  const TaskPauseState = IDL.Record({
    'pausedAt' : IDL.Text,
    'unpausedAt' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignUserRoleAsAdmin' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignSuperUserRole' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'bootstrapAdmin' : IDL.Func([], [IDL.Bool], []),
    'countTasksByStatus' : IDL.Func([], [IDL.Nat, IDL.Nat, IDL.Nat], ['query']),
    'createTask' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Principal,
          IDL.Text,
          Priority,
          FrequencyType,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteTask' : IDL.Func([IDL.Nat], [], []),
    'getAdminCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAllTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getAllUserProfiles' : IDL.Func([], [IDL.Vec(UserProfileEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCompletionDates' : IDL.Func([], [IDL.Vec(CompletionDate)], ['query']),
    'getMyTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(Task)], ['query']),
    'getTaskInstanceCompletions' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Int))],
        ['query'],
      ),
    'getTaskInstanceRemarks' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getTaskInstanceTimingStatuses' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Text))],
        ['query'],
      ),
    'getTaskPauseStates' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, TaskPauseState))],
        ['query'],
      ),
    'getTasksByEmployee' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Task)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasAnyAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerSuperUser' : IDL.Func([], [IDL.Bool], ['query']),
    'markTaskInstanceDone' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'pauseTask' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setTaskInstanceRemarks' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'setTaskInstanceTimingStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'unmarkTaskInstanceDone' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'unpauseTask' : IDL.Func([IDL.Nat], [], []),
    'updateTaskDetails' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateTaskStatus' : IDL.Func([IDL.Nat, TaskStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
