/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CompletionDate {
  'taskId' : bigint,
  'completionTimestamp' : bigint,
}
export interface CountByStatusResult {
  'done' : bigint,
  'todo' : bigint,
  'inProgress' : bigint,
}
export type FrequencyType = { 'none' : null } |
  { 'monthly' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export type TaskStatus = { 'done' : null } |
  { 'todo' : null } |
  { 'inProgress' : null };
export interface TaskV3 {
  'id' : bigint,
  'status' : TaskStatus,
  'assignee' : Principal,
  'frequencyDays' : string,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'targetDate' : string,
  'priority' : Priority,
  'frequency' : FrequencyType,
  'department' : string,
}
export interface UserProfile { 'name' : string, 'email' : string }
export interface UserProfileEntry {
  'principal' : Principal,
  'profile' : UserProfile,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRoleAsAdmin' : ActorMethod<[Principal, UserRole], undefined>,
  'bootstrapAdmin' : ActorMethod<[], boolean>,
  'countTasksByStatus' : ActorMethod<[], CountByStatusResult>,
  'createTask' : ActorMethod<
    [
      string,
      string,
      Principal,
      string,
      Priority,
      FrequencyType,
      string,
      string,
    ],
    bigint
  >,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAdminCount' : ActorMethod<[], bigint>,
  'getAllTasks' : ActorMethod<[], Array<TaskV3>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfileEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletionDates' : ActorMethod<[], Array<CompletionDate>>,
  'getMyTasks' : ActorMethod<[], Array<TaskV3>>,
  'getTask' : ActorMethod<[bigint], [] | [TaskV3]>,
  'getTasksByEmployee' : ActorMethod<[Principal], Array<TaskV3>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasAnyAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTaskStatus' : ActorMethod<[bigint, TaskStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];