/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CompletionDate {
  'taskId' : bigint,
  'completionTimestamp' : bigint,
}
export type FrequencyType = { 'none' : null } |
  { 'monthly' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface Task {
  'id' : bigint,
  'status' : TaskStatus,
  'assignee' : Principal,
  'frequencyDays' : string,
  'title' : string,
  'createdAt' : bigint,
  'description' : string,
  'targetDate' : string,
  'priority' : Priority,
  'frequency' : FrequencyType,
  'department' : string,
}
export interface TaskPauseState { 'pausedAt' : string, 'unpausedAt' : string }
export type TaskStatus = { 'done' : null } |
  { 'todo' : null } |
  { 'inProgress' : null };
export interface UserProfile { 'name' : string, 'email' : string }
export interface UserProfileEntry {
  'principal' : Principal,
  'profile' : UserProfile,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignUserRoleAsAdmin' : ActorMethod<[Principal, UserRole], undefined>,
  'assignSuperUserRole' : ActorMethod<[Principal, boolean], undefined>,
  'bootstrapAdmin' : ActorMethod<[], boolean>,
  'countTasksByStatus' : ActorMethod<[], [bigint, bigint, bigint]>,
  'createTask' : ActorMethod<
    [
      string,
      string,
      Principal,
      string,
      Priority,
      FrequencyType,
      string,
      string,
    ],
    bigint
  >,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAdminCount' : ActorMethod<[], bigint>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfileEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCompletionDates' : ActorMethod<[], Array<CompletionDate>>,
  'getMyTasks' : ActorMethod<[], Array<Task>>,
  'getTask' : ActorMethod<[bigint], [] | [Task]>,
  'getTaskInstanceCompletions' : ActorMethod<[], Array<[string, bigint]>>,
  'getTaskInstanceRemarks' : ActorMethod<[], Array<[string, string]>>,
  'getTaskInstanceTimingStatuses' : ActorMethod<[], Array<[string, string]>>,
  'getTaskPauseStates' : ActorMethod<[], Array<[bigint, TaskPauseState]>>,
  'getTasksByEmployee' : ActorMethod<[Principal], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasAnyAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerSuperUser' : ActorMethod<[], boolean>,
  'markTaskInstanceDone' : ActorMethod<[bigint, string], undefined>,
  'pauseTask' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setTaskInstanceRemarks' : ActorMethod<[string, string], undefined>,
  'setTaskInstanceTimingStatus' : ActorMethod<[string, string], undefined>,
  'unmarkTaskInstanceDone' : ActorMethod<[bigint, string], undefined>,
  'unpauseTask' : ActorMethod<[bigint], undefined>,
  'updateTaskDetails' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateTaskStatus' : ActorMethod<[bigint, TaskStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
