/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface Task {
  'id' : bigint,
  'status' : TaskStatus,
  'assignee' : Principal,
  'title' : string,
  'createdAt' : bigint,
  'dueDate' : string,
  'description' : string,
  'priority' : Priority,
}
export type TaskStatus = { 'done' : null } |
  { 'todo' : null } |
  { 'inProgress' : null };
export interface UserProfile { 'name' : string, 'email' : string }
export interface UserProfileEntry { 'principal' : Principal, 'profile' : UserProfile }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bootstrapAdmin' : ActorMethod<[], boolean>,
  'hasAnyAdmin' : ActorMethod<[], boolean>,
  'countAllTasksByStatus' : ActorMethod<[], [bigint, bigint, bigint]>,
  'countTasksByStatus' : ActorMethod<[], [bigint, bigint, bigint]>,
  'createTask' : ActorMethod<
    [string, string, Principal, string, Priority],
    bigint
  >,
  'deleteTask' : ActorMethod<[bigint], undefined>,
  'getAllTasks' : ActorMethod<[], Array<Task>>,
  'getAllUserProfiles' : ActorMethod<[], Array<UserProfileEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyTasks' : ActorMethod<[], Array<Task>>,
  'getTask' : ActorMethod<[bigint], [] | [Task]>,
  'getTasksByEmployee' : ActorMethod<[Principal], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateTaskStatus' : ActorMethod<[bigint, TaskStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];